package com.rafalzwiazek.todo.errors;

public enum ErrorUser {
    USER_EXISTS,
    USER_DOESNT_EXISTS,
    WRONG_PASSWORD,
    USER_SAVED, LOGIN_SUCCESSFUL, USERNAME_CANNOT_BE_BLANK, PASSWORD_CANNOT_BE_BLANK;
}
